### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by carvalho2707** [binance-exchange/binance-java-api#129]
Hi,

I know that this may not be an issue but I needed to ask anyway. 
Does this api or binance support oauth? So we can let other users login without api key and secret?

**Comment by joaopsilva** [comment]
Hi @carvalho2707 , OAuth is not supported by Binance.

**Comment by carvalho2707** [comment]
Hi @joaopsilva , thanks for the feedback.
So everything we do here will be just for our account or if the users decides to login into our app/website with their apikey and secret right?

**Comment by joaopsilva** [comment]
Hi @carvalho2707 , thanks for your question. Most of the API calls don't require an API key and/or secret. For instance, the ones which fetch market information about a specific asset. Only the trading or account-specific APIs require an API key and a secret, since these will essentially give you full control over the account, and is therefore not recommended to share them.

**Comment by wink** [comment]
+1 for OAuth support
