### ISSUE TITLE
Missing artifact com.binance.api:binance-api-client:jar:1.0.0

### ISSUE THREAD

**Issue by yogi-dmt** [binance-exchange/binance-java-api#149]
When i add the dependency maven cannot find the artifact?

**Comment by leechguy** [comment]
## Installation
1. Install library into your Maven's local repository by running `mvn install`
2. Add the following Maven dependency to your project's `pom.xml`:
```
<dependency>
  <groupId>com.binance.api</groupId>
  <artifactId>binance-api-client</artifactId>
  <version>1.0.0</version>
</dependency>
```

Did you perform step 1? Before you can do step 1 you need to do the undocumented step 0 which is cloning the repository locally so that you actually can do the `mvn install`.

I ran into the same issue and then found the following alternative solution in one of the answers here in the issue list. This is what I'm currently using to quickly get me going. However, you may want to stick with cloning the repo and compile yourself. This has the added benefit that you can pull fixes into your local repo. The maintainers of this repo seem to be slow in merging fixes provided by the community.

### Alternatively method
Add the following to your `pom.xml` file:

```
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
```

and add the following to the dependencies section:

```
<dependency>
  <groupId>com.github.binance-exchange</groupId>
  <artifactId>binance-java-api</artifactId>
  <version>master-SNAPSHOT</version>
</dependency>
```

**Comment by Serg-Maximchuk** [comment]
Why not put this info in README file so any developer can fetch latest official library from repository using build tool? I do not want to clone/compile/build it by myself since there is official library on binance-exchange repo, not an unknown user account. I had being using jar file (even I am still not sure how it appeared in my project, though it was before me) until it stopped working on prod some day because API changes: https://github.com/binance-exchange/binance-java-api/issues/157 and https://github.com/binance-exchange/binance-java-api/issues/221

**Comment by sheeeev66** [comment]
this didn't fix this issue for me. I am still getting the same error. how do I fix this?
