### ISSUE TITLE
Binance, what is going on?!

### ISSUE THREAD

**Issue by nibarulabs** [binance-exchange/binance-java-api#183]
First off, I am not slighting anyone's efforts here. They are all appreciated and I am thankful of the work. **Thank you!**

However, there are 10 PRs waiting (and some very critical - like #133) and over 30 issues.

I am not criticizing @joaopsilva or anyone else that has contributed at all, but what is the point of Binance accepting this project as official if it's not even _official_? And by that I mean, PRs merged, issues triaged timely, the dependency actually available on Maven Central. The Maven Central bug #3 goes back almost a year now (12/14/2017).

Binance has reported over $200m profit last quarter (according to Crypt Briefing: https://cryptobriefing.com/raining-cash-binance/), so I'm just wondering why there is not a full time team (or person) on any of the Binance api adapters? Unless of course, Binance api adapters are _not_ a priority 😞 ??? Are these not a priority?

Is there anyone at Binance that can provide a response to this?

@joaopsilva and contributors thank you again 🙏 for this project.

**Comment by joaopsilva** [comment]
Hi @nibarulabs , first of all, thank you for your suggestions. This is indeed a community maintained API, and I cannot answer on behalf of Binance. I'm currently the only maintainer for it, but I would gladly accept contributors that could perform some of the tasks that you have mentioned.

I have since cleaned-up the project and over 2/3s of the pending issues. It should be much more stable now. I appreciate everyone's efforts when creating pull requests to this projects, but unfortunately, I often lack the time to properly test them, and I have had instances in the past where some pull requests contained bugs and/or breaking changes. I would be more than happy if someone else could help with that, by commenting on the PRs, and providing unit tests for them, that would make it easier for me to verify their integrity.

As for issue #3, I did start it last year (https://issues.sonatype.org/browse/OSSRH-36611), but got blocked at a step where I would need someone from Binance to confirm that this project could be hosted under the group id `com.binance`. I did ask for this confirmation to the CTO at the time, but I haven't heard back since.

In any case, for a critical library such as this one that can directly manipulate funds from a user account, I would always suggest to download a local copy from Github, instead of relying on an artifact deployed to Maven Central, which could have been tampered, and not necessarily in sync with Github.
